# .github/workflows/snake.yml
name: Generate Snake
permissions:
  contents: write

on:
  schedule:
    - cron: "0 */6 * * *"    # every 6 hours
  workflow_dispatch:          # manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout your repo
      - uses: actions/checkout@v2

      # 2. Generate snake GIF + SVG
      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: maram-qais
          outputs: |
            dist/github-contribution-grid-snake.gif
            dist/github-contribution-grid-snake.svg

      # 3. (Optional) Verify dist folder
      - name: Debug dist
        run: |
          echo "Contents of dist:"
          ls -lah dist

      # 4. Push generated files back to master (keeps history on main)
      - name: Push to master
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true

      # 5. Publish dist to output branch for your README
      - name: Publish to output branch
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
